# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: saucelabs/stt-cypress-mocha-node:v0.1.3

    steps:
    # appears that checkout@v2 uses javascript which is not compatible 
    # with the included node version in the container image.
    - name: Checkout Code
      uses: actions/checkout@v1
      
    - name: Workaround for container permissions
      run: sudo chown -R $USER:$(id -gn $USER) /github/home
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: saucectl run
      env:
          BUILD_ID: ${{ github.run_id }}
          BUILD_ENV: GitHub Actions
